   /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;
import Models.*;
import Models.ConexionMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author TooDe
 */
public class frmAsignarPaquetes extends javax.swing.JFrame {
      Connection con = ConexionMySQL.getConnection();
   PreparedStatement ps = null;
    /** Creates new form frmagregado */
    public frmAsignarPaquetes() {
            initComponents();
 searchPaquetes();
 searchClientes();
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      rSCalendar1 = new rojeru_san.componentes.RSCalendar();
      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jLabel20 = new javax.swing.JLabel();
      btnAsignarPaquetes = new principal.MaterialButtomRectangle();
      btnCancelarAsignacion = new principal.MaterialButtomRectangle();
      btnSalirAsignarPaquetes = new principal.MaterialButtomRectangle();
      cboPaquete = new javax.swing.JComboBox<>();
      jLabel2 = new javax.swing.JLabel();
      cboCliente = new javax.swing.JComboBox<>();
      jLabel3 = new javax.swing.JLabel();
      DCDate = new rojeru_san.componentes.RSDateChooser();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setLocation(new java.awt.Point(350, 150));
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      jPanel2.setBackground(new java.awt.Color(0, 139, 205));

      jLabel20.setFont(new java.awt.Font("Century", 1, 30)); // NOI18N
      jLabel20.setForeground(new java.awt.Color(255, 255, 255));
      jLabel20.setText("Asignar paquetes a clientes");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel20)
            .addGap(88, 88, 88))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jLabel20)
            .addContainerGap(30, Short.MAX_VALUE))
      );

      btnAsignarPaquetes.setBackground(new java.awt.Color(106, 128, 225));
      btnAsignarPaquetes.setForeground(new java.awt.Color(255, 255, 255));
      btnAsignarPaquetes.setText("Asignar");

      btnCancelarAsignacion.setBackground(new java.awt.Color(27, 161, 96));
      btnCancelarAsignacion.setForeground(new java.awt.Color(255, 255, 255));
      btnCancelarAsignacion.setText("Cancelar");

      btnSalirAsignarPaquetes.setBackground(new java.awt.Color(221, 80, 68));
      btnSalirAsignarPaquetes.setForeground(new java.awt.Color(255, 255, 255));
      btnSalirAsignarPaquetes.setText("Salir");

      cboPaquete.setBackground(new java.awt.Color(255, 255, 255));
      cboPaquete.setForeground(new java.awt.Color(0, 0, 0));
      cboPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paquete", "Caja navideña", "Tanque", "Vino", "Spaguetis" }));
      cboPaquete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

      jLabel2.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(51, 51, 51));
      jLabel2.setText("Seleccione paquete");

      cboCliente.setBackground(new java.awt.Color(255, 255, 255));
      cboCliente.setForeground(new java.awt.Color(0, 0, 0));
      cboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Pedro", "Veneury", "Emely", "Juan" }));
      cboCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

      jLabel3.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(51, 51, 51));
      jLabel3.setText("Seleccione el cliente");

      DCDate.setForeground(new java.awt.Color(51, 51, 51));
      DCDate.setBgChooser(new java.awt.Color(106, 128, 225));
      DCDate.setColorBackground(new java.awt.Color(0, 139, 205));
      DCDate.setColorDiaActual(new java.awt.Color(221, 80, 68));

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(20, 20, 20)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(cboPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel2))
                  .addGap(27, 27, 27)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DCDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jLabel3)))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(82, 82, 82)
                  .addComponent(btnAsignarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnCancelarAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnSalirAsignarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(58, 58, 58)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cboPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(DCDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnSalirAsignarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnCancelarAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnAsignarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAsignarPaquetes().setVisible(true);
              
            }
        });
    }

   public void searchPaquetes() {

      try {

         ResultSet resultSet = null;

         ps = con.prepareStatement("SELECT * FROM paquetes");
         resultSet = ps.executeQuery();
         this.cboPaquete.removeAllItems();
        this.cboPaquete.addItem("Seleccione un paquete");
         while(resultSet.next()) {
           this.cboPaquete.addItem(resultSet.getString("nombre_paquetes"));
         }
        
      } catch (Exception e) {
         System.err.println(e);

      }

   }
   
   public void searchClientes() {
      

      try {

         ResultSet resultSet = null;

         ps = con.prepareStatement("SELECT * FROM clientes");
         resultSet = ps.executeQuery();
         this.cboCliente.removeAllItems();
        this.cboCliente.addItem("Seleccione un cliente");
         while(resultSet.next()) {
         
          
           this.cboCliente.addItem(resultSet.getString("nombre"));
        
         }
        
      } catch (Exception e) {
         System.err.println(e);

      }

   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   public rojeru_san.componentes.RSDateChooser DCDate;
   public principal.MaterialButtomRectangle btnAsignarPaquetes;
   public principal.MaterialButtomRectangle btnCancelarAsignacion;
   public principal.MaterialButtomRectangle btnSalirAsignarPaquetes;
   public javax.swing.JComboBox<String> cboCliente;
   public javax.swing.JComboBox<String> cboPaquete;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private rojeru_san.componentes.RSCalendar rSCalendar1;
   // End of variables declaration//GEN-END:variables

}
