/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author TooDe
 */
public class frmModificarpaquete extends javax.swing.JFrame {

   /**
    * Creates new form frmpaquete
    */
   public frmModificarpaquete() {
     
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      materialShadow1 = new efectos.MaterialShadow();
      materialShadow2 = new efectos.MaterialShadow();
      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      materialTextField1 = new principal.MaterialTextField();
      materialTextField2 = new principal.MaterialTextField();
      txtSearch = new de.craften.ui.swingmaterial.MaterialTextField();
      txtDescripcionModificarPaquetes = new de.craften.ui.swingmaterial.MaterialTextField();
      txtCodigoModificarPaquete = new de.craften.ui.swingmaterial.MaterialTextField();
      btnMoficarPaquetes = new principal.MaterialButtomRectangle();
      txtPesoModificarPaquetes = new de.craften.ui.swingmaterial.MaterialTextField();
      btnSalirModificarPaquetes = new principal.MaterialButtomRectangle();
      btnCancelarModificacionPaquete = new principal.MaterialButtomRectangle();
      txtNombreModificarPaquete = new de.craften.ui.swingmaterial.MaterialTextField();
      btnBusc = new principal.MaterialButtomRectangle();
      txtTipoPaquete = new de.craften.ui.swingmaterial.MaterialTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setBackground(new java.awt.Color(255, 255, 255));
      setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      setLocation(new java.awt.Point(250, 50));
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      jPanel2.setBackground(new java.awt.Color(0, 139, 205));

      jLabel1.setBackground(new java.awt.Color(204, 204, 204));
      jLabel1.setFont(new java.awt.Font("Century", 0, 30)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("Modificar paquetes");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(308, 308, 308))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(16, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(14, 14, 14))
      );

      materialTextField1.setHint("Codiggo");

      materialTextField2.setBackground(new java.awt.Color(153, 255, 153));
      materialTextField2.setToolTipText("");
      materialTextField2.setHint("Hola");
      materialTextField2.setLabel("Codigo");

      txtSearch.setForeground(new java.awt.Color(0, 0, 0));
      txtSearch.setToolTipText("");
      txtSearch.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtSearch.setHint("Digite código paquete");
      txtSearch.setLabel("Código paquete");

      txtDescripcionModificarPaquetes.setColumns(20);
      txtDescripcionModificarPaquetes.setForeground(new java.awt.Color(0, 0, 0));
      txtDescripcionModificarPaquetes.setToolTipText("");
      txtDescripcionModificarPaquetes.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtDescripcionModificarPaquetes.setHint("Descripción paquete");
      txtDescripcionModificarPaquetes.setInheritsPopupMenu(true);
      txtDescripcionModificarPaquetes.setLabel("Descripción paquete");

      txtCodigoModificarPaquete.setForeground(new java.awt.Color(0, 0, 0));
      txtCodigoModificarPaquete.setText("000-658FD6");
      txtCodigoModificarPaquete.setToolTipText("");
      txtCodigoModificarPaquete.setEnabled(false);
      txtCodigoModificarPaquete.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtCodigoModificarPaquete.setHint("Digite código");
      txtCodigoModificarPaquete.setLabel("Código paquete");

      btnMoficarPaquetes.setBackground(new java.awt.Color(106, 128, 225));
      btnMoficarPaquetes.setForeground(new java.awt.Color(255, 255, 255));
      btnMoficarPaquetes.setText("Modificar");

      txtPesoModificarPaquetes.setForeground(new java.awt.Color(0, 0, 0));
      txtPesoModificarPaquetes.setToolTipText("");
      txtPesoModificarPaquetes.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtPesoModificarPaquetes.setHint("Digite peso paquete");
      txtPesoModificarPaquetes.setLabel("Peso paquete");

      btnSalirModificarPaquetes.setBackground(new java.awt.Color(221, 80, 68));
      btnSalirModificarPaquetes.setForeground(new java.awt.Color(255, 255, 255));
      btnSalirModificarPaquetes.setText("Salir");

      btnCancelarModificacionPaquete.setBackground(new java.awt.Color(27, 161, 96));
      btnCancelarModificacionPaquete.setForeground(new java.awt.Color(255, 255, 255));
      btnCancelarModificacionPaquete.setText("Cancelar");

      txtNombreModificarPaquete.setForeground(new java.awt.Color(0, 0, 0));
      txtNombreModificarPaquete.setToolTipText("");
      txtNombreModificarPaquete.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtNombreModificarPaquete.setHint("Digite nombre");
      txtNombreModificarPaquete.setLabel("Nombre paquete");

      btnBusc.setBackground(new java.awt.Color(3, 93, 227));
      btnBusc.setForeground(new java.awt.Color(255, 255, 255));
      btnBusc.setText("Buscar");

      txtTipoPaquete.setForeground(new java.awt.Color(0, 0, 0));
      txtTipoPaquete.setToolTipText("");
      txtTipoPaquete.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtTipoPaquete.setHint("Digite tipo paquete");
      txtTipoPaquete.setLabel("Tipo paquete");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtCodigoModificarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(txtNombreModificarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtPesoModificarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(txtTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(68, 68, 68)
            .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(181, 181, 181)
                  .addComponent(btnMoficarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(14, 14, 14)
                  .addComponent(btnCancelarModificacionPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnSalirModificarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(230, 230, 230)
                  .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(btnBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(126, 126, 126)
                  .addComponent(txtDescripcionModificarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(105, 105, 105)
                  .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(26, 26, 26)
                  .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(306, 306, 306))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addGap(32, 32, 32)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(txtCodigoModificarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtPesoModificarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtNombreModificarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(68, 68, 68)
                  .addComponent(txtDescripcionModificarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(34, 34, 34)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnMoficarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnSalirModificarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnCancelarModificacionPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 43, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

      getAccessibleContext().setAccessibleParent(jPanel1);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(frmModificarpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(frmModificarpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(frmModificarpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(frmModificarpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new MenuPaquetes().modificarPaquetes();
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   public principal.MaterialButtomRectangle btnBusc;
   public principal.MaterialButtomRectangle btnCancelarModificacionPaquete;
   public principal.MaterialButtomRectangle btnMoficarPaquetes;
   public principal.MaterialButtomRectangle btnSalirModificarPaquetes;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private efectos.MaterialShadow materialShadow1;
   private efectos.MaterialShadow materialShadow2;
   private principal.MaterialTextField materialTextField1;
   private principal.MaterialTextField materialTextField2;
   public de.craften.ui.swingmaterial.MaterialTextField txtCodigoModificarPaquete;
   public de.craften.ui.swingmaterial.MaterialTextField txtDescripcionModificarPaquetes;
   public de.craften.ui.swingmaterial.MaterialTextField txtNombreModificarPaquete;
   public de.craften.ui.swingmaterial.MaterialTextField txtPesoModificarPaquetes;
   public de.craften.ui.swingmaterial.MaterialTextField txtSearch;
   public de.craften.ui.swingmaterial.MaterialTextField txtTipoPaquete;
   // End of variables declaration//GEN-END:variables
}
