/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author TooDe
 */
public class frmModificarStutusPaquetes extends javax.swing.JFrame {
   
   /**
    * Creates new form frmpaquete
    */
   public frmModificarStutusPaquetes() {
     
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      materialShadow1 = new efectos.MaterialShadow();
      materialShadow2 = new efectos.MaterialShadow();
      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      materialTextField1 = new principal.MaterialTextField();
      materialTextField2 = new principal.MaterialTextField();
      materialTextField3 = new de.craften.ui.swingmaterial.MaterialTextField();
      materialTextField4 = new de.craften.ui.swingmaterial.MaterialTextField();
      materialTextField5 = new de.craften.ui.swingmaterial.MaterialTextField();
      materialButtomRectangle1 = new principal.MaterialButtomRectangle();
      materialTextField7 = new de.craften.ui.swingmaterial.MaterialTextField();
      jComboBox1 = new javax.swing.JComboBox<>();
      materialButtomRectangle2 = new principal.MaterialButtomRectangle();
      materialButtomRectangle3 = new principal.MaterialButtomRectangle();
      materialTextField8 = new de.craften.ui.swingmaterial.MaterialTextField();
      materialTextField6 = new de.craften.ui.swingmaterial.MaterialTextField();
      materialTextField9 = new de.craften.ui.swingmaterial.MaterialTextField();
      materialTextField10 = new de.craften.ui.swingmaterial.MaterialTextField();
      jLabel2 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(255, 255, 255));
      setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      setLocation(new java.awt.Point(250, 50));
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      jPanel2.setBackground(new java.awt.Color(0, 139, 205));

      jLabel1.setBackground(new java.awt.Color(204, 204, 204));
      jLabel1.setFont(new java.awt.Font("Century", 0, 30)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("Cambiar status paquetes");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(204, 204, 204)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(jLabel1)
            .addContainerGap(16, Short.MAX_VALUE))
      );

      materialTextField1.setHint("Codiggo");

      materialTextField2.setBackground(new java.awt.Color(153, 255, 153));
      materialTextField2.setToolTipText("");
      materialTextField2.setHint("Hola");
      materialTextField2.setLabel("Codigo");

      materialTextField3.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField3.setText("00000-000005-5");
      materialTextField3.setToolTipText("");
      materialTextField3.setEnabled(false);
      materialTextField3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField3.setHint("Digite nombre");
      materialTextField3.setLabel("Cédula Cliente");

      materialTextField4.setColumns(20);
      materialTextField4.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField4.setText("Esto es una caja de zapatos para mi primo que vive en estados unidos");
      materialTextField4.setToolTipText("");
      materialTextField4.setEnabled(false);
      materialTextField4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField4.setHint("Descripción paquete");
      materialTextField4.setInheritsPopupMenu(true);
      materialTextField4.setLabel("Descripción paquete");

      materialTextField5.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField5.setText("000-GMKJS05");
      materialTextField5.setToolTipText("");
      materialTextField5.setEnabled(false);
      materialTextField5.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField5.setHint("Digite código");
      materialTextField5.setLabel("Código paquete");

      materialButtomRectangle1.setBackground(new java.awt.Color(106, 128, 225));
      materialButtomRectangle1.setForeground(new java.awt.Color(255, 255, 255));
      materialButtomRectangle1.setText("Cambiar");

      materialTextField7.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField7.setText("Devers Nolasco");
      materialTextField7.setToolTipText("");
      materialTextField7.setEnabled(false);
      materialTextField7.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField7.setHint("Digite peso paquete");
      materialTextField7.setLabel("Apellido cliente");

      jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
      jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
      jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Recojido", "Listo", "Entregado" }));
      jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

      materialButtomRectangle2.setBackground(new java.awt.Color(221, 80, 68));
      materialButtomRectangle2.setForeground(new java.awt.Color(255, 255, 255));
      materialButtomRectangle2.setText("Salir");

      materialButtomRectangle3.setBackground(new java.awt.Color(27, 161, 96));
      materialButtomRectangle3.setForeground(new java.awt.Color(255, 255, 255));
      materialButtomRectangle3.setText("Cancelar");

      materialTextField8.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField8.setText("50 Libras");
      materialTextField8.setToolTipText("");
      materialTextField8.setEnabled(false);
      materialTextField8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField8.setHint("Digite peso paquete");
      materialTextField8.setLabel("Nombre cliente");

      materialTextField6.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField6.setText("10-10-2018");
      materialTextField6.setToolTipText("");
      materialTextField6.setEnabled(false);
      materialTextField6.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField6.setHint("Digite código");
      materialTextField6.setLabel("Fecha asignado");

      materialTextField9.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField9.setText("Caja");
      materialTextField9.setToolTipText("");
      materialTextField9.setEnabled(false);
      materialTextField9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField9.setHint("Digite nombre");
      materialTextField9.setLabel("Tipo paquete");

      materialTextField10.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField10.setText("50 Libras");
      materialTextField10.setToolTipText("");
      materialTextField10.setEnabled(false);
      materialTextField10.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField10.setHint("Digite peso paquete");
      materialTextField10.setLabel("Peso paquete");

      jLabel2.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(51, 51, 51));
      jLabel2.setText("Seleccione nuevo status");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                     .addGap(15, 15, 15)
                     .addComponent(materialTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(18, 18, 18)
                     .addComponent(materialTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(18, 18, 18)
                     .addComponent(materialTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(18, 18, 18)
                     .addComponent(materialTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                     .addContainerGap()
                     .addComponent(materialTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(18, 18, 18)
                     .addComponent(materialTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(18, 18, 18)
                     .addComponent(materialTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(18, 18, 18)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(147, 147, 147)
                  .addComponent(materialButtomRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(14, 14, 14)
                  .addComponent(materialButtomRectangle3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(materialButtomRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addComponent(materialTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(materialTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(materialTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(materialTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(materialTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(23, 23, 23)
                  .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(26, 26, 26)
                  .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(41, 41, 41)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(materialTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(materialTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(materialTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGap(44, 44, 44)
            .addComponent(materialTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(materialButtomRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(materialButtomRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(materialButtomRectangle3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(27, 27, 27))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

      getAccessibleContext().setAccessibleParent(jPanel1);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(frmModificarStutusPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(frmModificarStutusPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(frmModificarStutusPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(frmModificarStutusPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new frmModificarStutusPaquetes().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox<String> jComboBox1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private principal.MaterialButtomRectangle materialButtomRectangle1;
   private principal.MaterialButtomRectangle materialButtomRectangle2;
   private principal.MaterialButtomRectangle materialButtomRectangle3;
   private efectos.MaterialShadow materialShadow1;
   private efectos.MaterialShadow materialShadow2;
   private principal.MaterialTextField materialTextField1;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField10;
   private principal.MaterialTextField materialTextField2;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField3;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField4;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField5;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField6;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField7;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField8;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField9;
   // End of variables declaration//GEN-END:variables
}
