/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author TooDe
 */
public class frmModificarpaquete extends javax.swing.JFrame {

   /**
    * Creates new form frmpaquete
    */
   public frmModificarpaquete() {
     
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      materialShadow1 = new efectos.MaterialShadow();
      materialShadow2 = new efectos.MaterialShadow();
      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      materialTextField1 = new principal.MaterialTextField();
      materialTextField2 = new principal.MaterialTextField();
      materialTextField3 = new de.craften.ui.swingmaterial.MaterialTextField();
      materialTextField4 = new de.craften.ui.swingmaterial.MaterialTextField();
      materialTextField5 = new de.craften.ui.swingmaterial.MaterialTextField();
      materialButtomRectangle1 = new principal.MaterialButtomRectangle();
      materialTextField7 = new de.craften.ui.swingmaterial.MaterialTextField();
      jComboBox1 = new javax.swing.JComboBox<>();
      materialButtomRectangle2 = new principal.MaterialButtomRectangle();
      materialButtomRectangle3 = new principal.MaterialButtomRectangle();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(255, 255, 255));
      setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      setLocation(new java.awt.Point(250, 50));
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      jPanel2.setBackground(new java.awt.Color(0, 139, 205));

      jLabel1.setBackground(new java.awt.Color(204, 204, 204));
      jLabel1.setFont(new java.awt.Font("Century", 0, 30)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("Modificar paquetes");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(308, 308, 308))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(16, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(14, 14, 14))
      );

      materialTextField1.setHint("Codiggo");

      materialTextField2.setBackground(new java.awt.Color(153, 255, 153));
      materialTextField2.setToolTipText("");
      materialTextField2.setHint("Hola");
      materialTextField2.setLabel("Codigo");

      materialTextField3.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField3.setText("Caja navideña");
      materialTextField3.setToolTipText("");
      materialTextField3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField3.setHint("Digite nombre");
      materialTextField3.setLabel("Nombre paquete");

      materialTextField4.setColumns(20);
      materialTextField4.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField4.setText("Paquete enviado por razón de agrado a mi madre.");
      materialTextField4.setToolTipText("");
      materialTextField4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField4.setHint("Descripción paquete");
      materialTextField4.setInheritsPopupMenu(true);
      materialTextField4.setLabel("Descripción paquete");

      materialTextField5.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField5.setText("000-658FD6");
      materialTextField5.setToolTipText("");
      materialTextField5.setEnabled(false);
      materialTextField5.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField5.setHint("Digite código");
      materialTextField5.setLabel("Código paquete");

      materialButtomRectangle1.setBackground(new java.awt.Color(106, 128, 225));
      materialButtomRectangle1.setForeground(new java.awt.Color(255, 255, 255));
      materialButtomRectangle1.setText("Modificar");

      materialTextField7.setForeground(new java.awt.Color(0, 0, 0));
      materialTextField7.setText("60 Libras");
      materialTextField7.setToolTipText("");
      materialTextField7.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      materialTextField7.setHint("Digite peso paquete");
      materialTextField7.setLabel("Peso paquete");

      jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
      jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caja", " ", " " }));
      jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

      materialButtomRectangle2.setBackground(new java.awt.Color(221, 80, 68));
      materialButtomRectangle2.setForeground(new java.awt.Color(255, 255, 255));
      materialButtomRectangle2.setText("Salir");

      materialButtomRectangle3.setBackground(new java.awt.Color(27, 161, 96));
      materialButtomRectangle3.setForeground(new java.awt.Color(255, 255, 255));
      materialButtomRectangle3.setText("Cancelar");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(materialTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(25, 25, 25)
            .addComponent(materialTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(materialTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(32, 32, 32)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(57, 57, 57)
            .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(181, 181, 181)
                  .addComponent(materialButtomRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(14, 14, 14)
                  .addComponent(materialButtomRectangle3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(materialButtomRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(156, 156, 156)
                  .addComponent(materialTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(105, 105, 105)
                  .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(26, 26, 26)
                  .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(306, 306, 306))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(materialTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(materialTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(materialTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(43, 43, 43)
                  .addComponent(materialTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(59, 59, 59)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(materialButtomRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(materialButtomRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(materialButtomRectangle3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 43, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

      getAccessibleContext().setAccessibleParent(jPanel1);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(frmModificarpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(frmModificarpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(frmModificarpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(frmModificarpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new frmModificarpaquete().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox<String> jComboBox1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private principal.MaterialButtomRectangle materialButtomRectangle1;
   private principal.MaterialButtomRectangle materialButtomRectangle2;
   private principal.MaterialButtomRectangle materialButtomRectangle3;
   private efectos.MaterialShadow materialShadow1;
   private efectos.MaterialShadow materialShadow2;
   private principal.MaterialTextField materialTextField1;
   private principal.MaterialTextField materialTextField2;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField3;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField4;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField5;
   private de.craften.ui.swingmaterial.MaterialTextField materialTextField7;
   // End of variables declaration//GEN-END:variables
}
