/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.ModelsMetodosPaquetes;
import Models.ModelsPaquetes;
import Views.frmpaquete;
import Controllers.ControllersPaquetes;

/**
 *
 * @author TooDe
 */
public class frmpaquete extends javax.swing.JFrame {

   /**
    * Creates new form frmpaquete
    */
   public frmpaquete() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      materialShadow1 = new efectos.MaterialShadow();
      materialShadow2 = new efectos.MaterialShadow();
      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      materialTextField1 = new principal.MaterialTextField();
      materialTextField2 = new principal.MaterialTextField();
      txtNombrepaquete = new de.craften.ui.swingmaterial.MaterialTextField();
      txtDescripcion = new de.craften.ui.swingmaterial.MaterialTextField();
      txtCodigopaquete = new de.craften.ui.swingmaterial.MaterialTextField();
      btnagregarpaquete = new principal.MaterialButtomRectangle();
      txtPesopaquete = new de.craften.ui.swingmaterial.MaterialTextField();
      btnsalirpaquetes = new principal.MaterialButtomRectangle();
      btncancelarPaquetes = new principal.MaterialButtomRectangle();
      btnNuevoTipoPaquetePaquetes = new principal.MaterialButtonCircle();
      cboTipopaquetes = new de.craften.ui.swingmaterial.MaterialComboBox();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(255, 255, 255));
      setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      setLocation(new java.awt.Point(250, 50));
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      jPanel2.setBackground(new java.awt.Color(0, 139, 205));

      jLabel1.setBackground(new java.awt.Color(204, 204, 204));
      jLabel1.setFont(new java.awt.Font("Century", 0, 30)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("Agregar paquetes");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(308, 308, 308))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(16, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(14, 14, 14))
      );

      materialTextField1.setHint("Codiggo");

      materialTextField2.setBackground(new java.awt.Color(153, 255, 153));
      materialTextField2.setToolTipText("");
      materialTextField2.setHint("Hola");
      materialTextField2.setLabel("Codigo");

      txtNombrepaquete.setForeground(new java.awt.Color(0, 0, 0));
      txtNombrepaquete.setToolTipText("");
      txtNombrepaquete.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtNombrepaquete.setHint("Digite nombre");
      txtNombrepaquete.setLabel("Nombre paquete");

      txtDescripcion.setColumns(20);
      txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
      txtDescripcion.setToolTipText("");
      txtDescripcion.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtDescripcion.setHint("Descripción paquete");
      txtDescripcion.setInheritsPopupMenu(true);
      txtDescripcion.setLabel("Descripción paquete");
      txtDescripcion.setScrollOffset(4);

      txtCodigopaquete.setForeground(new java.awt.Color(0, 0, 0));
      txtCodigopaquete.setToolTipText("");
      txtCodigopaquete.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtCodigopaquete.setHint("Digite código");
      txtCodigopaquete.setLabel("Código paquete");

      btnagregarpaquete.setBackground(new java.awt.Color(106, 128, 225));
      btnagregarpaquete.setForeground(new java.awt.Color(255, 255, 255));
      btnagregarpaquete.setText("Agregar");

      txtPesopaquete.setForeground(new java.awt.Color(0, 0, 0));
      txtPesopaquete.setToolTipText("");
      txtPesopaquete.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
      txtPesopaquete.setHint("Digite peso paquete");
      txtPesopaquete.setLabel("Peso paquete");

      btnsalirpaquetes.setBackground(new java.awt.Color(221, 80, 68));
      btnsalirpaquetes.setForeground(new java.awt.Color(255, 255, 255));
      btnsalirpaquetes.setText("Salir");

      btncancelarPaquetes.setBackground(new java.awt.Color(27, 161, 96));
      btncancelarPaquetes.setForeground(new java.awt.Color(255, 255, 255));
      btncancelarPaquetes.setText("Cancelar");

      btnNuevoTipoPaquetePaquetes.setBackground(new java.awt.Color(106, 128, 225));
      btnNuevoTipoPaquetePaquetes.setForeground(new java.awt.Color(255, 255, 255));
      btnNuevoTipoPaquetePaquetes.setText("+");
      btnNuevoTipoPaquetePaquetes.setToolTipText("Nueva tipo paquete");
      btnNuevoTipoPaquetePaquetes.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N

      cboTipopaquetes.setBackground(new java.awt.Color(255, 255, 255));
      cboTipopaquetes.setForeground(new java.awt.Color(102, 102, 102));
      cboTipopaquetes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo paquete", "Caja", "Tanque", "Cama" }));
      cboTipopaquetes.setAccent(new java.awt.Color(0, 188, 212));

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtCodigopaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(25, 25, 25)
            .addComponent(txtNombrepaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtPesopaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cboTipopaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnNuevoTipoPaquetePaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(43, 43, 43)
            .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(181, 181, 181)
                  .addComponent(btnagregarpaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(14, 14, 14)
                  .addComponent(btncancelarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnsalirpaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(156, 156, 156)
                  .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(105, 105, 105)
                  .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(26, 26, 26)
                  .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(306, 306, 306))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombrepaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigopaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPesopaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(cboTipopaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnNuevoTipoPaquetePaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(43, 43, 43)
                  .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(59, 59, 59)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnagregarpaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnsalirpaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btncancelarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 43, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

      getAccessibleContext().setAccessibleParent(jPanel1);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(frmpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(frmpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(frmpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(frmpaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            ModelsPaquetes modp = new ModelsPaquetes();
            ModelsMetodosPaquetes modmp = new ModelsMetodosPaquetes();
            frmpaquete frmp = new frmpaquete();
            ControllersPaquetes ctrl = new ControllersPaquetes(modp, modmp, frmp);
            ctrl.iniciar();
            frmp.setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   public principal.MaterialButtonCircle btnNuevoTipoPaquetePaquetes;
   public principal.MaterialButtomRectangle btnagregarpaquete;
   public principal.MaterialButtomRectangle btncancelarPaquetes;
   public principal.MaterialButtomRectangle btnsalirpaquetes;
   public de.craften.ui.swingmaterial.MaterialComboBox cboTipopaquetes;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private efectos.MaterialShadow materialShadow1;
   private efectos.MaterialShadow materialShadow2;
   private principal.MaterialTextField materialTextField1;
   private principal.MaterialTextField materialTextField2;
   public de.craften.ui.swingmaterial.MaterialTextField txtCodigopaquete;
   public de.craften.ui.swingmaterial.MaterialTextField txtDescripcion;
   public de.craften.ui.swingmaterial.MaterialTextField txtNombrepaquete;
   public de.craften.ui.swingmaterial.MaterialTextField txtPesopaquete;
   // End of variables declaration//GEN-END:variables
}
